### ISSUE TITLE
Error on execute $node token.js

### ISSUE THREAD

**Issue by iamdevnitesh** [BelkaDev/Spotify-JWT#6]
Following error is received when running node token.js
OS: Arch x86_64
Kernel: Linux-zen

```
$node token.js

Previous token expired or not found, generating a new one.
302
Refresh token has expired or was not retrieved.
/home/niteshk/Spotify-Headless/node_modules/puppeteer/lib/Launcher.js:211
      reject(new Error([
             ^

Error: Failed to launch chrome!
/home/niteshk/Spotify-Headless/node_modules/puppeteer/.local-chromium/linux-515411/chrome-linux/chrome: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/home/niteshk/Spotify-Headless/node_modules/puppeteer/lib/Launcher.js:211:14)
    at Interface.<anonymous> (/home/niteshk/Spotify-Headless/node_modules/puppeteer/lib/Launcher.js:200:50)
    at Interface.emit (node:events:402:35)
    at Interface.close (node:readline:586:8)
    at Socket.onend (node:readline:277:10)
    at Socket.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by BelkaDev** [comment]
Clone to #5
